#192.168.0.50
esphome:
  name: light_kitchen

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "5b6be67c0a7ee63602685a85cc43225f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Erty Fallback Hotspot"
    password: "m4DVA5bCRRk8"

captive_portal:


dallas:
  pin: GPIO2 #D4
  update_interval: 5s
  
  
sensor:
    platform: dallas
    name: "temp_test"
    address: 0xdc0014528cb9ff28
    
    
light:
  - platform: monochromatic
    name: "Kitchen Lights"
    output: output_component1
    default_transition_length: 3.0s
   # gamma_correct: 9.6
    
    

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    
    
    
    pin: GPIO12
    
    
#    min_power: 0.01
#    max_power: 0.99
   
