#192.168.0.35
esphome:
  name: ir-remote

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "6559727fd9d188dff311c055fe8ab29f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.0.35

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir-Remote Fallback Hotspot"
    password: "xxPQze5VtjwN"

captive_portal:

web_server:
  port: 80
  
#dallas:
#  pin: GPIO2 #D4
#  update_interval: 5s
  
  
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s 
    

  - platform: uptime
    id: device_uptime
      #    internal: true


text_sensor:
  - platform: template
    name: "Uptime"
    lambda: |-
      uint32_t uptime = (id(device_uptime).state);
      int minutes = (uptime % 3600) / 60;
      int hours = (uptime % 86400) / 3600;
      int days = uptime / 86400;
      if (days > 0) {
        return { (String(days) + " д." + String(hours) + " ч." + String(minutes) + " мин.").c_str() };
      }
      if (hours > 0) {
        return { (String(hours) + " ч. " + String(minutes) + " мин.").c_str() };
      } else {
          return { (String(minutes) + " мин.").c_str() };
        } 
    update_interval: 60s
    icon: mdi:clock-start              

status_led:
  pin: GPIO4

remote_receiver:
  pin: 
    number: GPIO5
    inverted: true
  dump: all

remote_transmitter:
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%
  id: "s06_transmitter"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
    name: "s06_button"
    id: "s06_button"
    

      
switch:
  - platform: template
    name: "OK"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xF20D
  - platform: template
    name: "On_Off"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF708
  - platform: template
    name: "Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xF40B
  - platform: template
    name: "Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xF00F
  - platform: template
    name: "Left"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xB649
  - platform: template
    name: "Right"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xB54A
  - platform: template
    name: "Vol+"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFD02
  - platform: template
    name: "Vol-"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFC03
  - platform: template
    name: "Back"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xFD02
  - platform: template
    name: "Mute"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF609

  - platform: template
    name: "lampa"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF906

 
        
        
    