esphome:
  name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
 # encryption:
#    key: "EzkT4rHY57I9t74eHNGQdnY2zEMo+1szEFSscx8ehhk="

ota:
#  password: "6d537067808b20aecc41fc5519986b47"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "Nzka6xuvGl1o"

captive_portal:


# Example configuration entry

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO0
    num_leds: 30
#    color_correct: [90%, 90%, 90%]
    #restore_mode: ALWAYS_ON
    name: "Test"
    id: my_light
    
    effects:
      - addressable_rainbow:    
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 1
          width: 30
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 5s
          update_interval: 10s



# Example configuration entry
# Example configuration entry
# Example configuration entry
sensor:
  - platform: resistance
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 4.6kOhm
    accuracy_decimals: 0
    name: photoresist

# Example source sensor:
  - platform: adc
    id: source_sensor
    update_interval: 1s
    pin: A0
    
    filters:
       - offset:  2.0
       - multiply:  1.1
