#192.168.0.40
esphome:
  name: xiaomi

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "846e63a45ee74634ddd3206f21b8fd78"

wifi: 
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  use_address: 192.168.0.40
#  power_save_mode: HIGH
  
  
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaomi Fallback Hotspot"
    password: "sS0Nw1vLO4oe"

captive_portal:

web_server:
  port: 80

#bluetooth_proxy:
#esp32_ble_tracker:
#xiaomi_ble:

sensor:

 - platform: wifi_signal
   name: "WiFi Signal Sensor"
   update_interval: 60s    
 
 
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO23
      inverted: false
      mode:
        input: true
        pullup: true
    name: "Состояние телевизора"  
       
# Example configuration entry

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO2
    num_leds: 192
    color_correct: [60%, 60%, 60%]
    #restore_mode: "Мой рандом"
    name: "Подсветка телевизора"
    
  

    effects:
      - addressable_rainbow:
          name: Радуга
      - addressable_rainbow:
          name: Моя радуга
          speed: 5
          width: 200
      - random:
          name: "Рандом"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Мой рандом"
          transition_length: 5s
          update_interval: 10s



   
   
   


